export const logos = [
  { src: "/logos/airtable.png", alt: "Airtable" },
  { src: "/logos/apollo.png", alt: "Apollo" },
  { src: "/logos/claude.png", alt: "Claude" },
  { src: "/logos/clay.png", alt: "Clay" },
  { src: "/logos/hubspot.png", alt: "HubSpot" },
  { src: "/logos/instantly.png", alt: "Instantly" },
  { src: "/logos/make.png", alt: "Make" },
  { src: "/logos/n8n.png", alt: "n8n" },
  { src: "/logos/openai.png", alt: "OpenAI" },
  { src: "/logos/phantombuster.png", alt: "PhantomBuster" },
  { src: "/logos/relevance.png", alt: "Relevance AI" },
  { src: "/logos/sendspark.png", alt: "SendSpark" },
  { src: "/logos/slack.png", alt: "Slack" },
  { src: "/logos/smartlead.png", alt: "Smartlead" },
  { src: "/logos/supabase.png", alt: "Supabase" },
  { src: "/logos/vapi.png", alt: "Vapi" },
  { src: "/logos/whatsapp.png", alt: "WhatsApp" },
  { src: "/logos/zapier.png", alt: "Zapier" },
]; 